# Generated by Django 5.2.7 on 2025-10-31 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.CharField(max_length=100, unique=True)),
                ('recipient_name', models.CharField(max_length=200)),
                ('course_name', models.CharField(max_length=200)),
                ('issued_date', models.DateField(auto_now_add=True)),
                ('blockchain_hash', models.CharField(max_length=256)),
                ('transaction_hash', models.CharField(blank=True, max_length=256, null=True)),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
