# Generated by Django 5.2.7 on 2025-10-31 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_authorized',
            field=models.BooleanField(default=False),
        ),
    ]
