# Generated by Django 5.2.7 on 2025-10-31 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_account_is_authorized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='private_key',
            field=models.TextField(),
        ),
    ]
